// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Node Manager Plugin API
//
//	API for handling local Massa node via Node Manager Plugin in MassaStation
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/png
//	  - text/css
//	  - text/html
//	  - text/javascript
//	  - application/json
//	  - text/event-stream
//	  - text/webp
//
// swagger:meta
package restapi
