// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for handling local Massa node via Node Manager Plugin in MassaStation",
    "title": "Node Manager Plugin API",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Handle the default page of the plugin",
        "operationId": "DefaultPage",
        "responses": {
          "302": {
            "description": "Redirect to /web"
          }
        }
      }
    },
    "/api/start": {
      "post": {
        "description": "Launch the massa node",
        "produces": [
          "application/json"
        ],
        "operationId": "StartNode",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/StartNodeBody"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Node launched"
          },
          "500": {
            "description": "Error launching node",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/status": {
      "get": {
        "description": "Get massa node status",
        "produces": [
          "application/json"
        ],
        "operationId": "GetMassaNodeStatus",
        "responses": {
          "200": {
            "description": "Current node status",
            "schema": {
              "$ref": "#/definitions/NodeStatus"
            }
          }
        }
      }
    },
    "/api/stop": {
      "post": {
        "description": "Stop the massa node",
        "produces": [
          "application/json"
        ],
        "operationId": "StopNode",
        "responses": {
          "204": {
            "description": ""
          },
          "500": {
            "description": "Error stopping node",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/web/{resource}": {
      "get": {
        "description": "Plugin Frontend router.",
        "produces": [
          "application/json",
          "text/javascript",
          "text/html",
          "text/css",
          "text/webp",
          "image/png"
        ],
        "operationId": "PluginWebApp",
        "parameters": [
          {
            "type": "string",
            "description": "Website resource.",
            "name": "resource",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Page found"
          },
          "404": {
            "description": "Resource not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "NodeStatus": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "running",
            "stopped",
            "starting",
            "stopping",
            "error"
          ]
        }
      }
    },
    "StartNodeBody": {
      "type": "object",
      "properties": {
        "useBuildnet": {
          "description": "Whether to launch the node in buildnet mode or not",
          "type": "boolean"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for handling local Massa node via Node Manager Plugin in MassaStation",
    "title": "Node Manager Plugin API",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Handle the default page of the plugin",
        "operationId": "DefaultPage",
        "responses": {
          "302": {
            "description": "Redirect to /web"
          }
        }
      }
    },
    "/api/start": {
      "post": {
        "description": "Launch the massa node",
        "produces": [
          "application/json"
        ],
        "operationId": "StartNode",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/StartNodeBody"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Node launched"
          },
          "500": {
            "description": "Error launching node",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/status": {
      "get": {
        "description": "Get massa node status",
        "produces": [
          "application/json"
        ],
        "operationId": "GetMassaNodeStatus",
        "responses": {
          "200": {
            "description": "Current node status",
            "schema": {
              "$ref": "#/definitions/NodeStatus"
            }
          }
        }
      }
    },
    "/api/stop": {
      "post": {
        "description": "Stop the massa node",
        "produces": [
          "application/json"
        ],
        "operationId": "StopNode",
        "responses": {
          "204": {
            "description": ""
          },
          "500": {
            "description": "Error stopping node",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/web/{resource}": {
      "get": {
        "description": "Plugin Frontend router.",
        "produces": [
          "application/json",
          "text/javascript",
          "text/html",
          "text/css",
          "text/webp",
          "image/png"
        ],
        "operationId": "PluginWebApp",
        "parameters": [
          {
            "type": "string",
            "description": "Website resource.",
            "name": "resource",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Page found"
          },
          "404": {
            "description": "Resource not found.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "NodeStatus": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "running",
            "stopped",
            "starting",
            "stopping",
            "error"
          ]
        }
      }
    },
    "StartNodeBody": {
      "type": "object",
      "properties": {
        "useBuildnet": {
          "description": "Whether to launch the node in buildnet mode or not",
          "type": "boolean"
        }
      }
    }
  }
}`))
}
