name: Install

inputs:
  # the input value is the 'runs-on'
  os:
    required: true
    default: "ubuntu-latest"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
        cache: true

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x

    - name: Install Dependencies
      run: |
        set -x
        echo "go bin before"
        ls -laR $HOME/go/bin
        task install
        echo "go bin after"
        ls -laR $HOME/go/bin
      shell: bash

    - name: build frontends and generate api files from spec
      shell: bash
      run: |
        set -x
        echo "go bin before"
        ls -laR $HOME/go/bin
        task generate
        echo "go bin after"
        ls -laR $HOME/go/bin
