name: Install

inputs:
  # the input value is the 'runs-on'
  os:
    required: true
    default: "ubuntu-latest"
  repo-token:
    description: The token to use to authenticate with the GitHub API
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
        cache: true

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x

    - name: Install Dependencies
      run: |
        task install
      shell: bash

    - name: build frontends and generate api files from spec
      shell: bash
      run: |
        task generate

