// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetNodeLogsHandlerFunc turns a function with the right signature into a get node logs handler
type GetNodeLogsHandlerFunc func(GetNodeLogsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNodeLogsHandlerFunc) Handle(params GetNodeLogsParams) middleware.Responder {
	return fn(params)
}

// GetNodeLogsHandler interface for that can handle valid get node logs params
type GetNodeLogsHandler interface {
	Handle(GetNodeLogsParams) middleware.Responder
}

// NewGetNodeLogs creates a new http.Handler for the get node logs operation
func NewGetNodeLogs(ctx *middleware.Context, handler GetNodeLogsHandler) *GetNodeLogs {
	return &GetNodeLogs{Context: ctx, Handler: handler}
}

/*
	GetNodeLogs swagger:route GET /api/nodeLogs getNodeLogs

Get the logs of the node
*/
type GetNodeLogs struct {
	Context *middleware.Context
	Handler GetNodeLogsHandler
}

func (o *GetNodeLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetNodeLogsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
