// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/node-manager-plugin/api/models"
)

// GetMassaNodeStatusOKCode is the HTTP code returned for type GetMassaNodeStatusOK
const GetMassaNodeStatusOKCode int = 200

/*
GetMassaNodeStatusOK Current node status

swagger:response getMassaNodeStatusOK
*/
type GetMassaNodeStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.NodeStatus `json:"body,omitempty"`
}

// NewGetMassaNodeStatusOK creates GetMassaNodeStatusOK with default headers values
func NewGetMassaNodeStatusOK() *GetMassaNodeStatusOK {

	return &GetMassaNodeStatusOK{}
}

// WithPayload adds the payload to the get massa node status o k response
func (o *GetMassaNodeStatusOK) WithPayload(payload *models.NodeStatus) *GetMassaNodeStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get massa node status o k response
func (o *GetMassaNodeStatusOK) SetPayload(payload *models.NodeStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMassaNodeStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
