// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/node-manager-plugin/api/models"
)

// StartNodeOKCode is the HTTP code returned for type StartNodeOK
const StartNodeOKCode int = 200

/*
StartNodeOK massa node launched with success

swagger:response startNodeOK
*/
type StartNodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.StartNodeResponse `json:"body,omitempty"`
}

// NewStartNodeOK creates StartNodeOK with default headers values
func NewStartNodeOK() *StartNodeOK {

	return &StartNodeOK{}
}

// WithPayload adds the payload to the start node o k response
func (o *StartNodeOK) WithPayload(payload *models.StartNodeResponse) *StartNodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start node o k response
func (o *StartNodeOK) SetPayload(payload *models.StartNodeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartNodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StartNodeInternalServerErrorCode is the HTTP code returned for type StartNodeInternalServerError
const StartNodeInternalServerErrorCode int = 500

/*
StartNodeInternalServerError Error launching node

swagger:response startNodeInternalServerError
*/
type StartNodeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStartNodeInternalServerError creates StartNodeInternalServerError with default headers values
func NewStartNodeInternalServerError() *StartNodeInternalServerError {

	return &StartNodeInternalServerError{}
}

// WithPayload adds the payload to the start node internal server error response
func (o *StartNodeInternalServerError) WithPayload(payload *models.Error) *StartNodeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start node internal server error response
func (o *StartNodeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartNodeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
