// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StopNodeHandlerFunc turns a function with the right signature into a stop node handler
type StopNodeHandlerFunc func(StopNodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn StopNodeHandlerFunc) Handle(params StopNodeParams) middleware.Responder {
	return fn(params)
}

// StopNodeHandler interface for that can handle valid stop node params
type StopNodeHandler interface {
	Handle(StopNodeParams) middleware.Responder
}

// NewStopNode creates a new http.Handler for the stop node operation
func NewStopNode(ctx *middleware.Context, handler StopNodeHandler) *StopNode {
	return &StopNode{Context: ctx, Handler: handler}
}

/*
	StopNode swagger:route POST /api/stop stopNode

Stop the massa node
*/
type StopNode struct {
	Context *middleware.Context
	Handler StopNodeHandler
}

func (o *StopNode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStopNodeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
