// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NodeStatus node status
//
// swagger:model NodeStatus
type NodeStatus struct {

	// status
	// Enum: ["on","off","bootstrapping","stopping","error"]
	Status string `json:"status,omitempty"`
}

// Validate validates this node status
func (m *NodeStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var nodeStatusTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["on","off","bootstrapping","stopping","error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		nodeStatusTypeStatusPropEnum = append(nodeStatusTypeStatusPropEnum, v)
	}
}

const (

	// NodeStatusStatusOn captures enum value "on"
	NodeStatusStatusOn string = "on"

	// NodeStatusStatusOff captures enum value "off"
	NodeStatusStatusOff string = "off"

	// NodeStatusStatusBootstrapping captures enum value "bootstrapping"
	NodeStatusStatusBootstrapping string = "bootstrapping"

	// NodeStatusStatusStopping captures enum value "stopping"
	NodeStatusStatusStopping string = "stopping"

	// NodeStatusStatusError captures enum value "error"
	NodeStatusStatusError string = "error"
)

// prop value enum
func (m *NodeStatus) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, nodeStatusTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *NodeStatus) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this node status based on context it is used
func (m *NodeStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodeStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeStatus) UnmarshalBinary(b []byte) error {
	var res NodeStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
