// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StartNodeResponse start node response
//
// swagger:model StartNodeResponse
type StartNodeResponse struct {

	// The version of the launched node
	Version string `json:"version,omitempty"`
}

// Validate validates this start node response
func (m *StartNodeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this start node response based on context it is used
func (m *StartNodeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StartNodeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StartNodeResponse) UnmarshalBinary(b []byte) error {
	var res StartNodeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
