// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StartNodeBody start node body
//
// swagger:model StartNodeBody
type StartNodeBody struct {

	// Whether to launch the node in buildnet mode or not
	UseBuildnet bool `json:"useBuildnet,omitempty"`
}

// Validate validates this start node body
func (m *StartNodeBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this start node body based on context it is used
func (m *StartNodeBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StartNodeBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StartNodeBody) UnmarshalBinary(b []byte) error {
	var res StartNodeBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
